#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

echo -n "Making sure pre-commit is up-to-date... "
diff -q assets/pre-commit ./.git/hooks/pre-commit >> /dev/null
if [[ "$?" != "0" ]]; then
    echo; echo "  Files don't match; updating hook. Please re-run commit."
    cp assets/pre-commit ./.git/hooks/pre-commit
    exit 1
fi
echo "✅"


echo -n "Runing gofmt and go vet... "
fmtfiles=$(gofmt -s -l .)
if [[ "${fmtfiles}" != "" ]]; then
    echo; echo "The following files need formatting:"
    echo "${fmtfiles}"
    echo "Please run 'gofmt -s -w .' and recommit"
    exit 1
fi
go vet
if [[ "$?" != "0" ]]; then
    exit 1
fi
echo "✅"

echo -n "Running golangci-lint... "
golangci-lint run --build-tags testing --exclude-files _test.go
if [[ "$?" != "0" ]]; then
    exit 1
fi
echo "✅"

echo -n "Running staticcheck... "
staticcheck
if [[ "$?" != "0" ]]; then
    exit 1
fi
echo "✅"

echo -n "Running tests... "
go test -tags testing . ./server ./client -coverpkg .,./server,./client -coverprofile=./assets/coverage
if [[ "$?" != "0" ]]; then
    exit 1
fi
go tool cover -html=./assets/coverage -o ./assets/coverage.html && rm ./assets/coverage
