#!/bin/bash
go test -tags testing . ./server ./client -coverpkg .,./server,./client -coverprofile=./assets/coverage
if [[ "$?" != "0" ]]; then
    exit 1
fi
go tool cover -html=./assets/coverage -o ./assets/coverage.html && rm ./assets/coverage
